version: '3'
services:
  mongodb:
    image: mongo:4.2
    networks:
      - my-network
    volumes:
      - mongodb-data:/data/db
  my-app:
    build: .
    networks:
      - my-network
    ports:
      - "8080:8080"
networks:
  my-network:
volumes:
  mongodb-data:

